CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" text UNIQUE NOT NULL,
  "password" text NOT NULL,
  "email" text UNIQUE NOT NULL,
  "rol" text NOT NULL
);

CREATE TABLE "status" (
  "status_id" int PRIMARY KEY,
  "description" text NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE NOT NULL
);

CREATE TABLE "designs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "artist_id" int NOT NULL,
  "category_id" int NOT NULL,
  "title" text NOT NULL,
  "description" text NOT NULL,
  "image_url" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "t_shirts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "design_id" int NOT NULL,
  "size_id" int NOT NULL,
  "color_id" int NOT NULL,
  "material_id" int NOT NULL,
  "type" text NOT NULL,
  "price" numeric(10,2) NOT NULL,
  "stock" int NOT NULL
);

CREATE TABLE "size" (
  "size_id" int PRIMARY KEY,
  "description" text NOT NULL
);

CREATE TABLE "material" (
  "material_id" int PRIMARY KEY,
  "description" text NOT NULL
);

CREATE TABLE "shopping_carts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "cart_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" int NOT NULL,
  "t_shirt_id" int NOT NULL,
  "quantity" int NOT NULL
);

CREATE TABLE "shipping_addresses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "address_line" text NOT NULL,
  "city" text NOT NULL,
  "state" text NOT NULL,
  "postal_code" text NOT NULL,
  "country" text NOT NULL
);

CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "shipping_address_id" int NOT NULL,
  "status" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "order_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "t_shirt_id" int NOT NULL,
  "quantity" int NOT NULL,
  "price" numeric(10,2) NOT NULL
);

CREATE TABLE "product_reviews" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "design_id" bigint NOT NULL,
  "rating" int NOT NULL,
  "comment" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "favorites" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "design_id" int NOT NULL
);

CREATE TABLE "payment_methods" (
  "id" int PRIMARY KEY,
  "user_id" int NOT NULL,
  "payment_type_id" int NOT NULL,
  "account_number" text,
  "is_default" bool DEFAULT (false)
);

CREATE TABLE "payments" (
  "id" int PRIMARY KEY,
  "order_id" int NOT NULL,
  "payment_methods_id" int NOT NULL,
  "amount" numeric(10,2) NOT NULL,
  "status" text NOT NULL,
  "transaction_id" text NOT NULL
);

CREATE TABLE "payment_type" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "desc" varchar NOT NULL
);

CREATE TABLE "shipments" (
  "id" int PRIMARY KEY,
  "order_id" int NOT NULL,
  "tracking" text NOT NULL,
  "carrier" text NOT NULL,
  "shipping_date" timestamp,
  "estimated_delivery" timestamp,
  "actual_delivery" timestamp,
  "status" text NOT NULL
);

CREATE TABLE "Colors" (
  "id" int PRIMARY KEY,
  "name" text NOT NULL,
  "hexcode" text NOT NULL
);

CREATE TABLE "Record" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type_id" int NOT NULL,
  "user_id" int NOT NULL,
  "order_id" int NOT NULL
);

CREATE TABLE "Type" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" text NOT NULL
);

ALTER TABLE "t_shirts" ADD FOREIGN KEY ("size_id") REFERENCES "size" ("size_id");

ALTER TABLE "designs" ADD FOREIGN KEY ("artist_id") REFERENCES "users" ("id");

ALTER TABLE "designs" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "t_shirts" ADD FOREIGN KEY ("design_id") REFERENCES "designs" ("id");

ALTER TABLE "shopping_carts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cart_id") REFERENCES "shopping_carts" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("t_shirt_id") REFERENCES "t_shirts" ("id");

ALTER TABLE "shipping_addresses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("shipping_address_id") REFERENCES "shipping_addresses" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("t_shirt_id") REFERENCES "t_shirts" ("id");

ALTER TABLE "product_reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "favorites" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("status") REFERENCES "status" ("status_id");

ALTER TABLE "payment_methods" ADD FOREIGN KEY ("payment_type_id") REFERENCES "payment_type" ("id");

ALTER TABLE "payment_methods" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("payment_methods_id") REFERENCES "payment_methods" ("id");

ALTER TABLE "shipments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "t_shirts" ADD FOREIGN KEY ("color_id") REFERENCES "Colors" ("id");

ALTER TABLE "favorites" ADD FOREIGN KEY ("design_id") REFERENCES "designs" ("id");

ALTER TABLE "t_shirts" ADD FOREIGN KEY ("material_id") REFERENCES "material" ("material_id");

ALTER TABLE "product_reviews" ADD FOREIGN KEY ("design_id") REFERENCES "designs" ("id");

ALTER TABLE "Record" ADD FOREIGN KEY ("type_id") REFERENCES "Type" ("id");

ALTER TABLE "Record" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "Record" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");
